name: Run Shell Script

on: [push]

jobs:
          run-script:
                      runs-on: ubuntu-latest

                          steps:
                                      - name: Checkout repository content
                                              uses: actions/checkout@v3

                                                  - name: Execute Shell Script
                                                          run: ./first-script.sh
                                                          
