name: Run Shell Script

on: 
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Execute Shell Script
        run: bash ./first-script.sh
